#开发配置
spring:
  datasource:
    name: nfsrm
#   url: jdbc:oracle:thin:@120.92.190.195:11521:ORCL
#   username: YONG_YAO_DEV
#   password: YONG_YAO_DEV
    url: jdbc:mysql://192.168.99.100:3306/nfsrm?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round&transformedBitIsBoolean=true 
    username: root
    password: 123456
#   driver-class-name: oracle.jdbc.driver.OracleDriver
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 50
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20